### ISSUE TITLE
Empty Website URL Remain Unchecked

### ISSUE THREAD

**Issue by lalxyy** [sindresorhus/generator-electron#24] opened 2016-07-19 01:53 UTC
I wrongly pressed <kbd>Enter</kbd> when asked for website URL, and the generator crashed. Would it be like asking for GitHub usernames, which warns user of the empty value?

```
? What is the URL of your website?

/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: Invalid URL
    at module.exports (/usr/local/lib/node_modules/generator-electron/node_modules/normalize-url/index.js:56:9)
    at Object.prompt.filter (/usr/local/lib/node_modules/generator-electron/app/index.js:34:12)
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/base.js:88:12
    at tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/rx/dist/rx.js:5883:51)
```

**Comment by sindresorhus** [comment] 2016-08-07 11:55
It used to work, but Inquirer (the prompt module) annoyingly decided to change the order of the `validate` and `filter` steps...

**Comment by sindresorhus** [comment] 2016-12-13 20:19
Can't reproduce this anymore. Must have been fixed in `Inquirer.js`.

**Closed as completed by sindresorhus** 2016-12-13 20:19 UTC
Labels: bug, help wanted
